version: '2'

services:
    postgres:
        restart: always
        image: postgres:9.5.4
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
            - ./docker/django/similarity.py:/docker/django/similarity.py
