# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated',
        ),
        migrations.AddField(
            model_name='country',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 0, 44, 12, 13000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AddField(
            model_name='university',
            name='country_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Country'),
        ),
    ]
