# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0002_auto_20171030_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='country_id',
            new_name='country',
        ),
    ]
