# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0007_usercoursepost_userfacultypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
