# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0008_auto_20171030_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Program')),
            ],
        ),
    ]
