# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-31 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0009_courseprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
