# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-31 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0010_remove_course_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Program'),
        ),
        migrations.AddField(
            model_name='programuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.University'),
        ),
        migrations.AddField(
            model_name='programfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Faculty'),
        ),
        migrations.AddField(
            model_name='programfaculty',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Program'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.City'),
            preserve_default=False,
        ),
    ]
