# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0011_auto_20171031_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.City')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Country')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Program')),
            ],
        ),
    ]
