# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0013_auto_20171114_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('first_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='csyllabusapi.Course')),
                ('second_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='csyllabusapi.Course')),
            ],
        ),
    ]
