# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0017_auto_20171213_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.Faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUniversityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('show', models.BooleanField(default=False)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csyllabusapi.University')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserFaculty',
            new_name='AdminFaculty',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachercourse',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercoursepost',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfacultypost',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
