# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0018_auto_20171216_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursepost',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
