# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0020_auto_20180108_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
