# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csyllabusapi', '0022_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='erased',
            field=models.BooleanField(default=False),
        ),
    ]
